http:
  port: "8081"
  
american:
  host: "training4-american-api-thomas1.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "38fbecb40d224bb0801e9ec4ae3cee99"
  client_secret: "E72CCc996B2348b4bA558a4D4a6CeC6B"
  
training:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"